import { useState } from "react";

import FileNode from "./FileNode";
import { IFileNode } from "./files";

interface IProps {
  files: IFileNode[];
}

const FileTree = (props: IProps) => {
  const { files } = props;
  // TODO generated by ai. Will cause the entire tree to be updated
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const handleToggle = (path: string) => {
    const newExpanded = new Set(expanded);
    if (expanded.has(path)) {
      newExpanded.delete(path);
    } else {
      newExpanded.add(path);
    }
    setExpanded(newExpanded);
  };

  return (
    <div className="text-sm">
      {files.map((file) => (
        <FileNode
          key={file.name}
          node={file}
          path={file.name}
          expanded={expanded}
          onToggle={handleToggle}
        />
      ))}
    </div>
  );
};

export default FileTree;
